server:
  port: 8086
#eureka:
#  instance:
#    prefer-ip-address: true
#  client:
#    service-url:
#      defaultZone: http://localhost:8761/eureka/
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/test1?characterEncoding=UTF-8
    username: root
    password: root123456
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
  application:
    name: user